language: node_js

node_js:
  - 13

services:
  - docker

install:
  - docker-compose -f monolith-to-microservices-project/docker-compose-build.yml build --parallel
  - docker-compose -f monolith-to-microservices-project/docker-compose-build.yml build push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


