language: node_js

node_js:
  - 13

services:
  - docker

install:
  - docker-compose -f monolith-to-microservices-project/docker-compose-build.yml build --parallel
  - docker build -t udagram-api-feed cloud-developer-workspace/monolith-to-microservices-project/udagram-api-feed
  - docker build -t udagram-api-feed cloud-developer-workspace/monolith-to-microservices-project/udagram-api-frontend
  - docker build -t udagram-api-feed cloud-developer-workspace/monolith-to-microservices-project/udagram-api-user
  - docker build -t udagram-api-feed cloud-developer-workspace/monolith-to-microservices-project/udagram-api-reverseproxy
  - docker tag udagram-api-feed waltongoga/udagram-api-feed:v1
  - docker tag udagram-frontend waltongoga/udagram-frontend:v1
  - docker tag udagram-api-user waltongoga/udagram-api-user:v1
  - docker tag reverseproxy waltongoga/reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push waltongoga/udagram-frontend:v1
  - docker push waltongoga/udagram-api-feed:v1
  - docker push waltongoga/udagram-api-user:v1
  - docker push waltongoga/reverseproxy:v1

