name: Docker Image CI

on:
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    env:
        NAME_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: NAME_USER
          password: DOCKER_PASS
          
      - name: Publish udagram-api-feed to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./monolith-to-microservices-project/udagram-api-feed
          push: true
          tags: waltongoga/udagram-api-feed:latest, waltongoga/udagram-api-feed:${{ github.run_number }}
          
      - name: Publish udagram-api-user to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./monolith-to-microservices-project/udagram-api-user
          push: true
          tags: waltongoga/udagram-api-user:latest, waltongoga/udagram-api-user:${{ github.run_number }}
          
      - name: Publish udagram-frontend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./monolith-to-microservices-project/udagram-frontend
          push: true
          tags: waltongoga/udagram-frontend:latest, waltongoga/udagram-frontend:${{ github.run_number }}
          
      - name: Publish reverseproxy to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./monolith-to-microservices-project/udagram-reverseproxy
          push: true
          tags: waltongoga/reverseproxy:latest, waltongoga/reverseproxy:${{ github.run_number }}